export const CART_ADD_ITEM = 'CARD_ADD_ITEM'
export const CART_DELETE_ITEM = 'CARD_DELETE_ITEM'
export const CART_SAVE_SHIPPING_ADDRESS = 'CARD_SAVE_SHIPPING_ADDRESS'
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'